### ISSUE TITLE
Use transform-runtime babel plugin to avoid errors due to Symbol.iterator === undefined

### ISSUE THREAD

**Issue by RishitKedia** [jhorowitz-firedrum/redux-ui#1]
Hey there, @jhorowitz-firedrum! 👋

First off, thanks for forking `redux-ui` and keeping the library alive. 🙏

So, I'm working on a cross-platform app using `React`, `React Native`, and `Expo`. Just moved over to `react-redux-ui-tools`, and everything's working great on `web` and `iOS`, but I'm getting the following error on `Android` when I open the app:

```
TypeError: undefined is not a function
(evaluating 'searchKeyPath[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
```

It points to: 

```
- node_modules/react-redux-ui-tools/dist/utils.js:157:12 in __getIn
- node_modules/react-redux-ui-tools/dist/utils.js:257:15 in getIn
- node_modules/react-redux-ui-tools/dist/ui.js:157:29 in componentWillMount
```

Any thoughts as to why this is occurring on `Android`? 😰

Thanks! 😃

**Comment by RishitKedia** [comment]
So, I've managed to fix this. It turns out that the error is occurring due to `react-redux-ui-tools`'s use of `Symbol.iterator` which is not being liked by `Android`.

## Solution

Polyfill `Symbol.iterator` with `babel-polyfill`.

```
yarn add babel-polyfill
```

In the entry point of the app, require `babel-polyfill`:
```js
require('babel-polyfill');
```

---

Closing this. Thanks! 🙃

**Comment by ghost** [comment]
Hi @RishitKedia!

Thanks for reporting this issue (and your kind words :) )

There were a couple ways to handle this...
Changing the documentation to point out the need for babel-polyfill in environments without Symbol.iterator, or by applying the babel transform-runtime plugin before distributing react-redux-ui-tools.

I opted for the latter, since it only adds a small amount of additional code bloat while keeping the library extremely easy to use.

Please let me know if v1.0.6+ allows you to compile and run on Android without the use of babel-polyfill.

Thank you!

**Comment by RishitKedia** [comment]
Hey, Jonathan! 👋

Just tried `v1.0.6`, and it works on `Android` without using `babel-polyfill`. Pretty cool! 🤘

Thank you for taking out the time to fix this! Cheers! 🙏
